Eigenfocus/eigenfocus

app/views/time_entries/_form_project_dependent_fields.html.erb

When creating a new time entry, selecting a project and pressing TAB the focus will go to the next input and not the Go To Board link.

Ignoring "Go To Board" link when using tab in Time Entry form

---

app/controllers/visualizations_controller.rb
app/javascript/controllers/grouping_column_controller.js
app/views/visualizations/_column.html.erb
app/views/visualizations/groupings/create.turbo_stream.erb
app/views/visualizations/show.html.erb

This PR implements:
- A new "Create Column" fixed on top of the board
- After a new column is created it scrolls to the newly created column
- The newly created column appears with an animation
- The board CSS implementation was refactored to use css grid instead of flexbox. This will be more flexible in the future if we want to show columns in different ways (different sizes and using rows)

feat(boards): UI/UX enhancements for creating new columns and cards

---

config.ru

This is worth doing because in some cases the user may want to expose the service to the internet and the reverse proxy used doesn't provide a quick/easy way to enable HTTP BASIC AUTH.
The server automatically uses HTTP BASIC AUTH if these 2 environments variables are set:
- `HTTP_AUTH_USER` - For the username 
- `HTTP_AUTH_PASSWORD` - For the password

feat: Implements optional http basic auth

---

app/controllers/visualizations/allocations_controller.rb
app/javascript/controllers/sortable_controller.js
app/views/visualizations/allocations/move.turbo_stream.erb
spec/features/managing_kanban_spec.rb

Before this change, the card HTML wasn't being updated so the card `<a>` link tag that points to it's detail form was still using the old group_id in the `href` attribute.
This caused a very nasty bug that you could reproduce by:
- Entering a board with multiple columns
- Move a card to another column
- Remove the old column
- Click in a card
- You will see a "Content missing" because Rails is responding with an error
The test was modified to fetch the new HTML element returned by the turbo_stream response. Otherwise capybara would show an error: stale element reference: stale element not found in the current frame
The route doesn't need to contain the grouping id so this will be refactored in the next PR. 
With the refactoring this fix isn't really necessary but it's still a good idea to …

fix(boards): updating card html after position changes

---

app/javascript/controllers/form_controller.js
app/views/time_entries/_form.html.erb
config/locales/actions.en.yml
config/locales/actions.pt-br.yml

If we want to start/edit a new time entry with a description it's quicker to hit CMD+Enter/CTRL+Enter than pressing tab or clicking on the create/update button.
This also changes the `form_controller.js` `FormController#submit` method to use the `requestSubmit()` polyfill to submit the form via JS.
https://github.com/hotwired/turbo/pull/439

feat(TimeEntry/Form): submit via keyboard shortcuts

---

app/controllers/visualizations/issues_controller.rb
app/controllers/visualizations_controller.rb
app/javascript/controllers/application.js
app/javascript/controllers/issue_detail_controller.js
app/views/visualizations/_card.html.erb
app/views/visualizations/issues/_form.html.erb
app/views/visualizations/show.html.erb
config/routes.rb

- We may want to favorite an Issue using the browser
- If more than one person is using the app it's very helpful to have a issue link to share
- This allows referencing issues inside another by writing the issue link in the description
- Issue now has a dedicated URL
- Opening an issue now advances the browser history
- Closing the issue modal advances the browser history to the `visualization/:id`
- The behavior of closing the issue modal with browser back history button scrolls the board to the first column.

feat(Issues): Issue URL navigation 

---

app/helpers/application_helper/icons.rb
app/views/projects/_project.html.erb
app/views/time_entries/_form_project_dependent_fields.html.erb
app/views/time_entries/_time_entry.html.erb
config/locales/app.en.yml
config/locales/app.pt-BR.yml

This PR: 
- Updates icons for boards and issues
- Add a link to the issue in the time entries list
- If the time entry has no issue a link to the board is shown instead

feat: link to issue from time entries list + icons update

---

spec/features/reports/time_report_spec.rb
spec/spec_helper.rb

During the last PR CI run, we notice that some tests fail without a reasonable explanation. However, we couldn't reproduce it (Neither local nor on CI).
So, assuming we can have other flaky tests, this PR setup tests to run in a random order.
Also, during this setup, one test fail and we could reproduce it, so it is already a win 🤷

Chore: Setup random repeatable tests

---

app/channels/application_cable/channel.rb
app/channels/application_cable/connection.rb
app/javascript/application.js
app/javascript/channels/consumer.js
app/javascript/channels/index.js
app/views/layouts/application.html.erb
config/cable.yml
config/database.example.yml
config/importmap.rb
config/routes.rb
db/cable_schema.rb
spec/features/managing_kanban_spec.rb

While using Eigenfocus with more than one tab open at the same time is possible, it would be even better if some updates would reflect on already open pages.
This is specially true for pages like the board view and timesheet.
So this PR setup Action Cable, which enables WebSocket connections that we can use to solve the mentioned issue.
- Add `SolidCable` to allow ActionCable use the SQLite database instead of adding something like Redis as a dependency
- Configure the cable database (Used by `SolidCable` adapter)
- Add basic setup for creating ActionCable channels

Chore: Setup Action Cable - First step for real-time app

---

Gemfile
Gemfile.lock
app/controllers/time_entries_controller.rb
app/models/time_entry.rb
app/views/time_entries/_time_entry.html.erb
app/views/time_entries/create.turbo_stream.erb
app/views/time_entries/index.html.erb

As explained [before](https://github.com/Eigenfocus/eigenfocus/pull/40), we are making the UX better by making pages update their content in real-time.
This PR adds this behavior on the Time Tracking page
- Add missing SolidCable gem
- Add `broadcasts_to` to time entries model
- Change index "no time entry" panel to appear/disappear based on CSS sibling selector, instead of depend on HTML updates

Feat: Live updates on time tracking page

---

Gemfile
Gemfile.lock
app/assets/tailwind/themes/base.css
app/assets/tailwind/themes/pagy.tailwind.css
app/controllers/application_controller.rb
app/controllers/projects/issues_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/labels.rb
app/helpers/application_helper/page_title.rb
app/models/issue.rb
app/views/projects/_project.html.erb
app/views/projects/issues/_issue.html.erb
app/views/projects/issues/index.html.erb
app/views/visualizations/show.html.erb
config/initializers/pagy.rb
config/initializers/ransack.rb
config/locales/activerecord.en.yml
config/locales/activerecord.pt-BR.yml
config/locales/app.en.yml
config/locales/app.pt-BR.yml
config/locales/page_title.en.yml
config/locales/page_title.pt-BR.yml
config/locales/ransack.en.yml
config/locales/ransack.pt-BR.yml
config/routes.rb

As a project grows, the number of issues and columns increases. It becomes much harder to get an overview of all issues and manage multiple ones at once using the board view.
To help with that, we’re introducing a new visualization called "All Issues": our good old reliable issue list with forms, search, sorting and all the handy features that our projects deserves.
- Add `pagy` and `ransack` to help with pagination and filtering, respectively
- Create navigation bar to easily switch between board and list view
- Later we can refactory that to actually have a reusable component for this navigation
- Create a helper for showing labels
- Add the project issue list, adding a link on the board view to this page

Feat: Project all issues listing

---

app/assets/tailwind/themes/base.css
app/helpers/application_helper/labels.rb
app/javascript/controllers/visualization/issue_filtering_controller.js
app/models/issue_label.rb
app/models/issue_label_link.rb
app/views/visualizations/_card.html.erb
app/views/visualizations/show.html.erb
config/importmap.rb
config/locales/activerecord.en.yml
config/locales/activerecord.pt-BR.yml
config/locales/page_title.en.yml
config/locales/page_title.pt-BR.yml
spec/features/project_management/kanban/filtering_issues_spec.rb
spec/features/project_management/kanban/managing_issues_data_spec.rb
vendor/javascript/fuse.js.js

As part of our effort to enhance the experience for solo users (and even small teams sharing same workspace!) on the FREE Edition, we're introducing a more intuitive way to manage complex projects. With this feature, we're adding an instant issue search to the Workflow Board, making it easier to find issues quickly by title and labels.
We can now filter issues/cards by their title and labels using a single text input field. The search is fuzzy, case-insensitive, ignores accentuation and word order. This makes searching more flexible and user-friendly. 
- Introduces fuse.js to handle fuzzy search.
- Implements a new issue_filtering_controller.js Stimulus controller for filtering issues.
- The show/hide behavior is managed via a data-is-issue-search-match attribute and CSS.
- UI tweaks to …

feat(Boards): issues filtering by title and labels

---

app/assets/tailwind/themes/select2.css
app/javascript/controllers/select2_controller.js

This PR fixes the select2 custom behavior to hide selected options from search result list. 
The old implementation was buggy because It was hiding options that were not really selected yet because the `aria-selected` is applied to a 'focused' option while navigating through the search result list. 
This was also causing some specs to fail.
In order to solve this, we need to intercept the original search matcher to ignore already selected options

fix(select2): hiding selected option from search result

---

app/channels/visualizations/allocations_channel.rb
app/channels/visualizations/groupings_channel.rb
app/javascript/controllers/visualization/board_controller.js
app/models/grouping.rb

As discussed [here](https://github.com/Eigenfocus/eigenfocus/pull/43#discussion_r1943709340), our initial channel implementation could be improved by making the stream id more flexible by accepting the action that the consumer is subscribing to, for example:
```rb
"visualizations:123:groupings#update"
```
Also, by interpolating a params to this format, the client can easily choose to subscribe to more than one action in the same channel too.
- Change stream id namespace separator from `/` to `:`
- Add action as part of the subscription params and using on the stream id
- Change model callbacks to always broadcast on update, as it is not binded to the "move" concept anymore

Refactory: Channel stream formats

---

app/assets/tailwind/themes/_components/all.css
app/assets/tailwind/themes/_components/button.css
app/assets/tailwind/themes/_components/link.css
app/assets/tailwind/themes/_components/table.css
app/assets/tailwind/themes/base.css
app/assets/tailwind/themes/select2.css
app/javascript/controllers/select2_controller.js
app/views/layouts/application.html.erb
app/views/projects/_navigation_header.html.erb
app/views/projects/issues/_filter.html.erb
app/views/projects/issues/_issue.html.erb
app/views/projects/issues/index.html.erb
app/views/visualizations/_board_header.html.erb
app/views/visualizations/show.html.erb
config/initializers/ransack.rb
config/locales/app.en.yml
config/locales/app.pt-BR.yml
config/locales/ransack.en.yml

This PR: 
- Creates a `project_header` partial to be reused among different views (it automatically selects the current tab). 
- Improves `select2` to accept custom classes to enable using styles different from the default one
- Changes the Board and All Issues to use the `project_header` tab navigation
- Updates the entire "All issues" UI (filter + table) by making everything more compact
- Redesign the "all issues" filter to be more compact and extracts the HTML to be in a partial, change labels and removes blank option from tags filter
- Changes table design to be more compact
- Extracts table styles to a dedicated component css file
- Changes the table to better indicate that sorting is allowed with ransack icons configuration (pending in future PR to align the header with the icon) …

WIP: feat: UI improvements and and refactors for Issues visualizations

---

app/assets/tailwind/themes/pagy.tailwind.css
app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/custom_pagy.rb
app/views/projects/issues/index.html.erb
config/initializers/pagy.rb

This PR: 
- Changes Pagy css styles 
- Setup Pagy I18n translations.
- Creates a `pagy_summary(pagy)` helper method to render the our entire pagination information
- Changes pagination limit to 50

chore(pagination): UI styles + i18n translations

---

app/assets/tailwind/themes/_components/button.css
app/controllers/projects/issues_controller.rb
app/controllers/visualizations_controller.rb
app/javascript/controllers/visualization/favorite_issue_labels_controller.js
app/models/visualization.rb
app/views/visualizations/_board_header.html.erb
app/views/visualizations/_card.html.erb
app/views/visualizations/_favorite_labels_dropdown.html.erb
app/views/visualizations/show.html.erb
app/views/visualizations/update.turbo_stream.erb
config/locales/actions.en.yml
config/locales/actions.pt-br.yml
config/locales/activerecord.en.yml
config/locales/activerecord.pt-BR.yml
config/locales/app.pt-BR.yml
config/locales/page_title.pt-BR.yml
config/locales/ransack.pt-BR.yml
config/routes.rb
db/migrate/20250209120105_add_favorite_issue_labels_to_visualizations.rb
db/schema.rb
spec/features/project_management/kanban/using_favorite_labels_spec.rb
spec/models/visualization_spec.rb

This PR introduces great enhancements to the Workflow Board and improves the label/issue management usability:
- Adds a dropdown for favorite issue labels directly on the board.
- Implements keyboard shortcuts (1–6) to apply or remove a favorite label from a card by hovering over it.
- Reverts PT-BR translations to use "Labels" instead of "Rótulos."
- Fixes the label search logic in the Projects::IssuesController to be case-insensitive.
- Adds a `favorite_issue_labels` to visualizations, which can be updated via the VisualizationsController#update action
- Creates a reusable favorite_issue_labels_controller.js within the visualizations namespace.
- The stimulus controller is inside the visualizations namespace
- Although the feature could be reused on the the 'All Issues' view, …

feat(Board/FavoriteLabels): keyboard shortcuts to apply/remove labels

---

app/channels/application_cable/channel.rb
app/channels/visualizations/allocations_channel.rb
app/channels/visualizations/groupings_channel.rb
app/helpers/application_helper.rb
app/helpers/application_helper/websockets_security.rb
app/javascript/controllers/visualization/board_controller.js
app/views/visualizations/show.html.erb
lib/stream_signer.rb
spec/lib/stream_signer_spec.rb

This PR improves websocket security (not too relevant here but it would be useful for the PRO/hosted edition) by providing an interface for connecting using a token instead of raw params. This, together with other verifications that should be done on the other editions, should prevent an undesirable listener to connect to non authorized channels. 
- When manually connection to a stream, we should send a token that contains the params instead of sending the raw parameters
- The token can be generated using a `signed_stream_token` helper method
- The token is validated on the `ApplicationCable::Channel` class in a `before_subscribe` hook 
- It configures a `signed_params` to be used on the child classes

chore: websockets security

---

app/controllers/reports_controller.rb
app/models/issue.rb
app/models/time_entry.rb
app/views/reports/_total_time/_filters.html.erb
app/views/reports/_total_time/_report.html.erb
config/locales/actions.en.yml
config/locales/actions.pt-br.yml
spec/features/reports/time_report_spec.rb

This PR implements the ability to generate a time report using issue labels. It shows a multiselect with all the existing labels for the user to choose from.

feat: time report filter by label

---

app/controllers/projects/issues_controller.rb
app/javascript/controllers/issue_detail_controller.js
app/javascript/controllers/markdown_controller.js
app/views/issues/_create.html.erb
app/views/issues/_description_field.html.erb
app/views/issues/_issue_detail.html.erb
app/views/projects/issues/_filter.html.erb
app/views/projects/issues/_issue.html.erb
app/views/projects/issues/create.turbo_stream.erb
app/views/projects/issues/index.html.erb
app/views/projects/issues/new.html.erb
config/locales/actions.en.yml
config/locales/actions.pt-br.yml
spec/features/managing_kanban_spec.rb
spec/features/project_management/all_issues/managing_issues_spec.rb
spec/support/helpers/markdown_editor.rb

This PR changes some behaviors and refactor code for the "Create new issue" workflow from "All issues" list. 
- It's now only using turbo and not turbo streams (it redirects the user to the listing and loses the current sorting. This makes sense as the new default sorting is the `updated_at` attribute)
- Fixed missing translations for issue deletion by moving the key to a top position in the translation file
- Implemented a generic `markdown` stimulus controller
- Extracted the description markdown field to a `issues/_description_field` partial. 
- Changed `/issues/_issue_detail` to use the new `issues/_description_field` partial. 
- Created a `/issues/_create.html.erb` partial to be used on `Projects::IssuesController#new`
- Created specs for issue creation from all issues
- Removed old …

chore: workflow changes "Create new issue" from "All Issues" List

---

app/controllers/issues_controller.rb
app/controllers/projects/issues_controller.rb
app/models/grouping.rb
app/models/grouping_issue_allocation.rb
app/models/issue.rb
app/views/issues/_issue_detail.html.erb
app/views/issues/issue_detail/_grouping_picker.html.erb
app/views/issues/pick_grouping.turbo_stream.erb
app/views/projects/issues/_issue.html.erb
app/views/projects/issues/index.html.erb
config/locales/actions.en.yml
config/locales/actions.pt-br.yml
config/locales/activerecord.en.yml
config/locales/activerecord.pt-BR.yml
config/locales/app.en.yml
config/locales/app.pt-BR.yml
config/routes.rb
spec/features/managing_kanban_spec.rb
spec/features/project_management/all_issues/managing_issues_spec.rb

While the workflow board shows which column each issue belongs, in the all issues view there was no such thing. More than that, when an issue is created, it defaults to a "No column" state. This means means it doesn't appear on the workflow board (yet :eyes:), and so we couldn't changs its column from there.
This PR fixes that! Now, you can change an issue’s column directly from the issue detail modal. No need to switch to the workflow board just to move it around! 
- Add grouping picker on the issue detail, you can change the column just selecting another one from the dropdown list
- After the update, the issue detail is updated via turbo frame
- Add has_many association from issue to grouping through grouping_issue_allocations (Used mainly by ransack filter)

Feat: Allow column to be choose from issue detail modal/form

---

app/models/grouping_issue_allocation.rb
app/models/issue.rb

When deleting an issue on one tab, the corresponding card was not removed from the workflow visualization on another tab
When deleting an issue on one tab, the corresponding card should also be removed from workflow visualization on another tab
When changing the assigned column to an issue on one tab, the corresponding issue was not removed from the workflow visualization on another tab (As there are no column for the issue to be)
When changing the assigned column to an issue on one tab, the corresponding issue should be removed from the workflow visualization on another tab
There was a misconfigured after_destroy broadcast for the issue modal, however, instead of changing it for only issue events, we moved the broadcast to the allocation.
1. This means that when an issue is destroyed, so …

Fix: Issue and column removal broadcast

---

app/models/issue_label.rb

This PR is just some little improvements on the `IssueLabel` model:
- Explicit downcase the `title` on the `with_title` to avoid problems with the SQLite `LIKE` that is case insensitive only for ASCII characters ([Reference](https://www.sqlite.org/lang_expr.html#the_like_glob_regexp_match_and_extract_operators))
- Change the manual normalization of label titles with the Rails 7 `ActiveRecord::Base.normalizes` ([Reference](https://www.bigbinary.com/blog/rails-7-1-adds-activerecord-base-normalizes))
While the `strip` is the desired normalization for the `title`, the downcase is not.
The reason for that is that we want to keep the original label case, as wrote by the user. So it should only be used for searches

Chore: Improve objectiveness

---

spec/features/project_management/kanban/using_favorite_labels_spec.rb
spec/support/capybara.rb

Once in a while tests fails, some times its our fault, others not exactly...
Locally, I notice that some tests would break from time to time because the button was hidden behind some other element, which doesn't happen on the usual development cycle.
But what happen is that during development we usually use a full size windows, while Capybara use a fixed size window. So increasing it should probably improve reliability (3261bdce9a37791b45fdf7bce62f24cd176944e6)
Another problem that happen from time to time is that a resource that should be updated, isn't. (spec/features/project_management/kanban/using_favorite_labels_spec.rb). This happen because we dispatch an action (click button/submit form) and while that is happening on the Browser (through Capybara), the test already go on, trying …

Chore: Improve tests reliability

---

spec/features/project_management/using_views/kanban/applying_issue_labels_spec.rb
spec/features/project_management/using_views/kanban/filtering_issues_spec.rb
spec/features/project_management/using_views/kanban/managing_groupings_spec.rb
spec/features/project_management/using_views/kanban/managing_issues_spec.rb
spec/features/project_management/using_views/kanban/using_favorite_labels_spec.rb

This PR moves kanban specs to other folders and files with more semantic names.

ref: moves kanban specs to a more semantic folder

---

app/views/projects/issues/_filter.html.erb
app/views/projects/issues/index.html.erb
config/locales/app.en.yml
config/locales/app.pt-BR.yml
spec/features/project_management/all_issues/managing_issues_spec.rb

This PR:
- adds a custom message if the search returns zero results.
- changes display breakpoint for the filters

Custom message for empty search on "All Issues"

---

app/controllers/profiles_controller.rb
app/services/example_project_creator.rb
app/views/issues/_issue_detail.html.erb
app/views/issues/issue_detail/_grouping_picker.html.erb
app/views/time_entries/index.html.erb
config/locales/app.en.yml
config/locales/app.pt-BR.yml
config/locales/examples/project.en.yml
config/locales/examples/project.pt-BR.yml
spec/features/managing_profile_spec.rb
spec/features/managing_projects_spec.rb
spec/features/project_management/all_issues/managing_issues_spec.rb
spec/support/helpers/should_be_on.rb

This PR introduces a key feature to improve user experience during onboarding
When the user user complete their profile for the first time, we now automatically create an example project that serves as an interactive tutorial. 
- Reduced modal width
- Added a "Start Time tracking" button (this can be improved in the future when we implement the current running time entries)
- Moved the column change select picker to the right
- Updated should_be_on spec helper method to include querystring

Onboarding Example Project & Quick Time Tracking

---

app/controllers/projects/issues_controller.rb
app/models/issue.rb
app/views/issues/_create.html.erb
spec/features/project_management/all_issues/managing_issues_spec.rb
spec/models/issue_spec.rb

Previously, labels could only be added after an issue was created, requiring additional steps to properly categorize issues. This workflow improvement allows users to set labels during issue creation, making the process more efficient and encouraging better issue organization from the beginning.
- Added a label picker field to the issue creation form
- Implemented labels_list method in the Issue model to handle label creation/assignment
- Labels can be input as comma-separated text or selected from existing labels

Apply labels from issue create modal

---

app/controllers/visualizations/groupings_controller.rb
app/javascript/controllers/grouping_column_controller.js
app/views/visualizations/_column.html.erb
db/migrate/20250228114444_add_collapsed_to_groupings.rb
db/migrate/20250228114444_add_hidden_to_groupings.rb
db/schema.rb
spec/features/project_management/using_views/kanban/collapsable_columns_spec.rb

Now you can collapse columns that you're not actively using. More Space, Less Clutter! 
Sometimes you only need to focus on specific columns (like "TODO/DOING/DONE") while having other columns such as "Release 1 - Backlog", "Release 2 - Backlog", "Finished Items" etc. 
Large projects with many columns can become overwhelming and require horizontal scrolling so this feature comes into hand to solve this issue. 
- Added a collapse/expand toggle button in each column's header
- Column titles rotate vertically when collapsed to maintain readability
- Issues are not rendered for collapsed columns
- The collapse behavior is propagated in real time to other clients
- In the next PR we will refactor the board style to a dedicated CSS component and use just a 'board-collapsed' css class to …

Feat board column expand

---

Dockerfile
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/jobs/new_version_check_job.rb
bin/jobs
config/database.example.yml
config/environments/development.rb
config/environments/production.rb
config/puma.rb
config/queue.yml
config/recurring.yml
db/queue_schema.rb
lib/app_version_updater.rb
spec/lib/app_version_updater_spec.rb

Currently, we execute the logic to check for a new version using a thread and - despite the fact that it works - it is not ideal because we depend on user interaction to do it.
Not only that: the trigger for this check happens on every action users perform on the system, which is unnecessary.
This PR creates an background job environment for running these kind of logic and changes the check new version logic to one that doesn't depend on user interaction.
- Configure SolidQueue
- Move logic to trigger version check to a Job
- Remove logic related to version expiration in favor to explicit recurring scheduling
- Configure background job to run along puma on production environments (as this avoid changing the project setup for existing users)

feat: live updates + new version checks using background jobs

---

lib/app_version_updater.rb
lib/self_hosted_api_client.rb

This PR implements a client class to the self hosted api. 
- Implementes `SelfHostedApiClient` with the new API endpoint
- Changes AppVersionUpdater to use the client

chore: implements self hosted api client 

---

app/jobs/eigenfocus_notifications_fetcher_job.rb
spec/jobs/eigenfocus_notifications_fetcher_job_spec.rb

In case some notifications are published with typo or incorrect text, we want to update those for the users, instead of leaving incorrect.
This PR changes the Notification creation logic to perform an upsert instead of an  exclusive insert, which means that if an existing notification (identified by its external ID) already exists in the system, it is going to be updated instead of skipped

Feat: Change notification logic to allow for corrections

---

app/controllers/projects/base_controller.rb
app/controllers/projects/issue_labels_controller.rb
app/controllers/projects/issues_controller.rb
app/controllers/visualizations/allocations_controller.rb
app/controllers/visualizations/base_controller.rb
app/controllers/visualizations/groupings_controller.rb
app/controllers/visualizations/issues_controller.rb
app/views/visualizations/_column.html.erb
config/routes.rb

This refactory is just to make our code base more consistency, by adding a BaseController on the visualizations and projects scope, so that shared methods are reused instead of copy/pasted.
No change in behavior is expected after merging this PR
- Move allocations controller as a nested resource for visualizations
- Create base controller for visualizations
- Create base controller for projects

Chore/Refac: Improve consistency between visualizations/projects controllers

---

app/controllers/application_controller.rb
app/controllers/projects/issue_labels_controller.rb
app/controllers/projects/issues_controller.rb
app/controllers/projects_controller.rb
app/controllers/time_entries_controller.rb
app/views/projects/index.html.erb
app/views/projects/issue_labels/index.html.erb
app/views/projects/issues/index.html.erb
app/views/time_entries/index.html.erb

This PR implements a way for using the 'new/edit' buttons in new browser tabs. This was implemented for:
- Time entries
- All Issues
- Issue Labels
- Projects

chore: keep entity listed when opening 'new/edit' modal forms in new browser tab

---

app/javascript/initializers/turbo_stream/dispatch_event.js
config/initializers/turbo_stream.rb

To make debugging easier, we are changing the dispatch event turbo stream tag to use a script tag with the JSON inside it.

Chore: Refactory dispatch event to send json in a script tag

---

app/assets/tailwind/themes/_components/all.css
app/assets/tailwind/themes/_components/markdown-editor/all.css
app/assets/tailwind/themes/_components/markdown-editor/common.css
app/assets/tailwind/themes/_components/markdown-editor/components/all.css
app/assets/tailwind/themes/_components/markdown-editor/components/code.css
app/assets/tailwind/themes/_components/markdown-editor/components/divider.css
app/assets/tailwind/themes/_components/markdown-editor/components/image.css
app/assets/tailwind/themes/_components/markdown-editor/components/link.css
app/assets/tailwind/themes/_components/markdown-editor/components/list.css
app/assets/tailwind/themes/_components/markdown-editor/components/quote.css
app/assets/tailwind/themes/_components/markdown-editor/components/table.css
app/assets/tailwind/themes/_components/markdown-editor/components/typograph.css
app/assets/tailwind/themes/_components/markdown-editor/prosemirror-tables.css
app/assets/tailwind/themes/_components/markdown-editor/prosemirror.css
app/assets/tailwind/themes/_components/markdown-editor/variables.css
app/views/issues/_create.html.erb
app/views/issues/_issue_detail.html.erb
frontend/components/MarkdownEditor.js
frontend/components/MarkdownEditor/configure/image-block.js
frontend/components/MarkdownEditor/configure/link-tooltip.js
frontend/components/MarkdownEditor/configure/menu.js
frontend/components/MarkdownEditor/configure/table-block.js
spec/features/project_management/all_issues/managing_issues_spec.rb
spec/features/project_management/using_views/kanban/managing_issues_spec.rb
spec/support/helpers/markdown_editor.rb

This PR brings the new markdown editor with more robust and future proof features.
This editor It's already integrated on the PRO Edition and It is configured with:
- Formatting support (Bold, italic, strikethrough)
- Headings
- Coding blocks
- Support for undo and redo commands (CTRL + Z & CTRL + SHIFT + Z)
- Links
- Quotes
- Divisor line
- Lists (Ordered, unordered)
- Checklists
- Table
- And even images (External ones, directly upload doesn't work yet...)

chore: Adds new markdown editor

---

app/assets/tailwind/themes/_components/visualizations/board.css
app/javascript/controllers/grouping_column_controller.js
app/views/visualizations/_column/_inline_card_form.html.erb

Now, when we hover "Create issue" button the press n tip appears
Now, if the column is showing the card form, the "Create issue" button dissapear

Fixes board "Create issue" button behaviour

---

app/javascript/app-tours/projects_tours.en.js
app/javascript/app-tours/projects_tours.pt-BR.js
app/views/projects/index.html.erb
frontend/components/FocusApp.js
spec/features/app_tour_spec.rb

This PR: 
- Removes the "Add project" explanation step
- Adds "Focus App" explanation step
- Fixes wrong pt-br translations

Adds focus space step to guided tour

---

app/views/layouts/application.html.erb
app/views/projects/_navigation_header.html.erb

This PR disables turbo cache for the entire application. 
https://turbo.hotwired.dev/handbook/building#opting-out-of-caching
Previously, we were noticing page flickers when navigating to pages with a slower response time. This was due to the old page being rendered from the browser cache and then the new page being rendered from the server after the response came in.
This PR disables the cache for all turbo pages to avoid any future problems. 
It also removes "turbo-preload" from the navigation header. It's already disabled by default. 
The test was made by simulating latency with
```ruby
before_action -> {
puts "sleeping"
sleep 0.6
puts "done sleeping"
}
```
https://github.com/user-attachments/assets/ac8fb770-aaa1-42fd-bcd8-c7489df08a09 …

chore: disables turbo cache

---

app/services/project/templatable/template_applier.rb

The logic without the position being manually set was causing delay for the position to be correctly updated and if I created a project using a template and instantly go to the workflow board the columns would take a while to be ordered.

chore: manually setting grouping position during template usage

---

app/assets/tailwind/themes/_components/focus-app/focus-app.css
frontend/components/FocusApp.js
frontend/components/FocusSpace/FocusSpace.js
frontend/components/FocusSpace/PomodoroTimer/PomodoroTimer.js

This PR:
- Refactors pomodoro timer logic to be more state machine like
- Changes pomodoro events props to have only one `onStateChange` prop
On Focus Space button:
- Adds a ping notification when a timer has finished
- Keeps pomodoro icon showing even if the timer is pause (it's not the sabe as being stopped)

Better ui and ux for focus space

---

bin/docker-entrypoint

This function is no longer needed for the v1.0.0

chore: removes deprecated database migration function

---

app/controllers/projects_controller.rb
app/views/visualizations/show.html.erb

When navigating to the board the request is being prefetched and the cached content is rendered after clicking the Workflow Link. 
This can lead to a quick "column reordening" because the view rendered by rails wasn't rendering columns following their position and, after the cached being rendered in the browser, it would take a few ms for the sortable library to correctly reorder the columns. 
With this change, this doesn't happen anymore.
The messages were being sent with lag so if the user quickly navigate to the board, the browser would receive the messages from the create action and mess with the board. 
The suppress methods must be called from the outside of any transaction so we're leaving it in the controller. We can decide to move it later to some model callback.

chore: change columns render order in board visualization

---

app/helpers/application_helper/modal.rb

During development of the latest features, we end up changing the modal styles for each page/component, so it would better fit the context and intention.
However, we accidentally remove the relative CSS class for modals with custom styles/sizes. And that causes the X button of some modals to appear on the top-right corner.

Fix: Modal X position broke after modal changes

---

app/views/layouts/_sidebar.html.erb
app/views/layouts/_sidebar/_projects_menu.html.erb
config/locales/application.layout.en.yml
config/locales/application.layout.pt-BR.yml
spec/views/layouts/_sidebar/projects_menu.html.erb_spec.rb

As our workspace grows with multiple projects, it's nice to have a quick way to take a look at the list of projects and add a new one.
So, this PR updates the sidebar to: 
- Always list the workspace projects (alphabetically and only active ones)
- Have an "Add project" button
- Have a "List all projects" link
- A new partial `_projects_menu.html.erb` was created to render the projects menu in the sidebar. Not worth trying to reuse the menu group (actually it may be worth deleting it)
- There's a max-height (300px) set for the list. After that, the browser scrollbar appears

chore: Project quick access from sidebar

---

docker-compose.dev.example.yml

Current chromium (134) is causing a lot of intermittent failures in our specs. So I'm punishing it by downgrading it to a version that (hopefully) won't break things.
For reference:
https://github.com/teamcapybara/capybara/issues/2800
https://github.com/teamcapybara/capybara/issues/2796
https://issues.chromium.org/issues/402796660

Downgrade selenium/standalone-chrome image

---

app/javascript/controllers/sidebar_controller.js
app/views/layouts/_header.html.erb
app/views/layouts/_sidebar.html.erb
app/views/layouts/_sidebar/_projects_menu.html.erb

This PR enhances the sidebar menu experience to be more practical for project navigation.
- Auto expand the collapsed sidebar on mouse hover
- Minor adjustments to project list font size/spacing
- Adds a 'pin/unpin' button to keep it expanded permanently
- Adds a link (to the root path) on our beautiful Eigenfocus logo

Sidebar menu enhancements

---

.ruby-gemset
app/controllers/visualizations/groupings_controller.rb
app/views/visualizations/_column.html.erb
app/views/visualizations/groupings/archive_all_issues.turbo_stream.erb
config/locales/actions.en.yml
config/locales/actions.pt-br.yml
config/locales/app.en.yml
config/locales/app.pt-BR.yml
config/routes.rb
spec/features/project_management/using_views/kanban/archive_all_issues_spec.rb

Some times we want to perform actions in bulk, like move all issues from one column to another. This is great when we need to move all our great work to a different column. 
As projects progress, finished issues tends to accumulate, usually in a collapsed column like "Done" or even "Archived".
Now, we go even further: 
This PR adds the ability to archive all issues from a column, so we can easily hide multiple issues from the board when the're were finished or just needs to be archived for no specific reason.
> Archive is not the same as deleting a column!
Deleting a column moves the issue to a "No column" state, but if you want you can still move them to another column after and they will be displayed on the board.
Archive means the issues shouldn't appear on the board anymore. You can …

Implements "Archive all" on boards

---

app/assets/tailwind/themes/flatpickr.css
app/controllers/projects/issues_controller.rb
app/controllers/visualizations/issues_controller.rb
app/helpers/application_helper.rb
app/helpers/application_helper/due_date.rb
app/helpers/application_helper/modal.rb
app/javascript/controllers/application.js
app/models/issue.rb
app/views/issues/_issue_detail.html.erb
app/views/issues/issue_detail/_right_sidebar.html.erb
app/views/projects/issues/_filter.html.erb
app/views/projects/issues/_issue.html.erb
app/views/projects/issues/index.html.erb
app/views/visualizations/_card.html.erb
config/locales/activerecord.en.yml
config/locales/activerecord.pt-BR.yml
config/locales/app.pt-BR.yml
config/locales/ransack.en.yml
config/locales/ransack.pt-BR.yml
db/migrate/20250430151615_add_due_date_to_issues.rb
db/schema.rb
spec/features/project_management/all_issues/listing_issues_spec.rb
spec/features/project_management/using_views/kanban/managing_issues_spec.rb
spec/support/helpers/flatpickr.rb
spec/support/helpers/modal.rb

Time is always running, it never stops. Wouldn't it be nice if we could know when that task should be finished?
Well, now we can!
This PR adds the `due date` field to the issues, so we can keep on track of how close things are to their delivery or even when that big event is going to happen.
The due date color changes based on how close the due date is. This way we can easily spot issues that may need our attention
- Red for issues overdue or within 1 day to the due date
- Yellow for issues within 1 to 3 days to the due date
- Default text color otherwise

feat: Issue due date

---

spec/support/helpers/turbo_confirm.rb

After introducing custom alert modals for `data-confirm`, some specs started failing inconsistently.
The issue was that `accept_alert` was being called inside `within` blocks, which prevented Capybara from properly detecting the `confirm-accept` button.
Fun fact: the button was being found sometimes, but not always... making debugging extra fun. 👀

test: Fixes flaky specs caused by custom data-confirm modals

---

bin/docker-entrypoint
config/environments/production.rb

- Changes rails log level to warn
- Updates docker entrypoint no need to manually trap sigterms as `bin/bin` is starting the rails server using `exec`.

Adjustments to production setup

---

example.env
frontend/components/HelloWorld.js
frontend/shared/date-format.js
package.json
yarn.lock

Our next features requires a lot of date formatting in the frontend React app. 
This PR adds `date-fns` lib that automatically formats dates based on the user's preferred language.
Build on shakapacker was displaying this message:
> ⚠️ WARNING
> Setting 'useContentHash' to 'false' in the production environment (specified by NODE_ENV environment variable) is not allowed!
> Content hashes get added to the filenames regardless of setting useContentHash in 'shakapacker.yml' to false.
So I've changed `example.env` to have NODE_ENV set to development

chore: adds i18n for dates on frontend app

---

app/javascript/controllers/application.js
app/views/issues/issue_detail/_right_sidebar.html.erb
app/views/reports/_total_time/_filters.html.erb
app/views/time_entries/index.html.erb

In the future we may add a `data-flatpickr-date-format="<%= t("date.formats.flatpickr") %>"` to the html tag and localize flatpickr dates but, for now, it's not worth the effort.

Adds a default date format to flatpickr

---

app/assets/tailwind/themes/_components/issue-label.css
app/helpers/application_helper/labels.rb

Befor, depending on the luminosity chosen for the label, the text was not readable. 
Now, the text color is set relative to the background color using css blend modes. Ideally we should use CSS `color-contrast` but it's an experimental feature yet. 
OR, we probably should add a text color option to the label

Dynamically sets label text colors via css

---

app/assets/tailwind/themes/_components/issue-label.css
app/helpers/application_helper/labels.rb

The labels crud uses Rails label ViewHelpers to render labels. Just like the board cards. 
I've decided to replicate the JS logic that we're using in our React label component on the Rails backend so the labels texts are rendered with the correct contrast depending on the background brightness.

chore: Seting label text color in the backend

---

app/javascript/initializers/turbo_confirm/index.js

This PR fixes a behaviour where if I click on an element with `data-confirm` and press "Enter/Return" it would open 'multiple modals' with many backdrop backgrounds

fix: data-confirm modal blurs clicked button on show

---

app/views/issues/_create.html.erb
app/views/issues/comments/_form.html.erb
app/views/issues/issue_detail/_main_form.html.erb
frontend/components/IssueDetail/Description.js
frontend/components/MarkdownEditor.js

The comments are rendered as a markdown editor (read only).
After this was implemented, a strange bug appeared where only the last markdown editor of the page rendered the header menu. 
This PR fixes that by creating a dedicated component for editing issues (this alone fixes the bug)
But additionally:
- I've changed the way that hidden inputs refs are handled also updates all 'markdown bindings' to have a more unique id or passing a ref to the input itself (if another React component is using the MarkdownEditor)
- Now that we have a dedicated IssueDetail editor we can make the description field read only and only turn to "editable" after the user clicks on it. Also it's possible to track changes and warn if the user tries to close the modal before submitting the changes
Before:

Enhancements to issue detail markdown field

---

app/controllers/issues_controller.rb
app/views/issues/_create.html.erb
app/views/issues/_files_drop.html.erb
app/views/issues/issue_detail/_main_form.html.erb
config/routes.rb
frontend/components/IssueDetail/Description.js
frontend/components/MarkdownEditor.js
package.json
spec/features/project_management/all_issues/managing_issues_spec.rb
spec/features/project_management/using_views/kanban/managing_issues_spec.rb
yarn.lock

This PR improves the overall Issue Detail modal usability:
- Making the Description markdown component readonly at start
- If the user clicks on the field or on the edit button, it turns to editable mode
- If the user cancel the edit, it goes back to the old value
- If the user saves the edit, it updates the text only field
- I've created a specific 'update_coment' endpoint. It may help us in the future to deal with potential conflicts when more than one people update the description at the same time.

Changes issue description to be a "text only" by default

---

app/javascript/controllers/grouping_column_controller.js
app/views/visualizations/issues/create.turbo_stream.erb

This PR solves an issue where cards keep getting forced to scroll into view when it has some data updated
When a card is created or updated it is always scrolled into view.
Card should only be scrolled into view when created ONLY for the session that created it. (Ex: When mutiple tabs open on the same board, only the board used to create the issue should scroll the issue into view)

Fix issue with scroll into view for new cards

---

config/locales/frontend-components/issue_detail.en.yml
config/locales/frontend-components/issue_detail.pt-BR.yml
frontend/components/IssueDetail/Description.js
frontend/components/MarkdownEditor.js
frontend/shared/utils/use-local-state.js

It happens with everybody. I am positive it already happened with you too...
While writing about very important on a website, after checking for every spell mistake, when everything looks fine and all, for some reason you close the tab and lost everything.
Maybe it was a misclick? Maybe the energy went off? Who knows?
When that happens, all we can do is smile... Smile like this person
So this PR help us avoid smiling like that by storing temporary changes on the issue details locally, so we can go back and actually save the descriptions we were writing.
Changes as discarded when cancelling the editing

Issue description storing temporary description

---

app/assets/tailwind/themes/_components/issue/card.css
app/helpers/application_helper/due_date.rb
app/helpers/application_helper/issues.rb
app/javascript/controllers/visualization/board/card_controller.js

After finishing the https://github.com/Eigenfocus/eigenfocus/pull/217, we notice we forgot to update the due date based on the issue been finished or not.
So this PR fixes that

Style due date based on the finished state

---

app/assets/tailwind/themes/_components/issue/all.css
app/assets/tailwind/themes/_components/issue/card.css
app/assets/tailwind/themes/_components/issue/finish-toogle.css
app/controllers/issues_controller.rb
app/helpers/application_helper/issues.rb
app/javascript/controllers/issue/finish_toogle_controller.js
app/views/issues/_issue_detail.html.erb
app/views/visualizations/_card.html.erb
spec/features/issues/mark_as_finished_spec.rb
spec/features/project_management/using_views/kanban/mark_as_finished_spec.rb

This PR:
- Refactor the "issue finished check" to a "Issue finish toggle" concept
- Refactor `_card` partial to:
-  just use a normal div with the stimulus controller attached instead of a helper
- be independent of the "issue-finished-toggle" component by animating a wrapper and not the toggle itself
- Refactor the `issue_detail`:
- To make the "finished toggle" and the "title input" independent of each other. The old implementation was using a helper and a block containing the title input. It was a little confusing what was happening there as this is not needed...
- Refactor the way that things are animated when a card is hovered to not be dependent on JS
- Adjusts margins, alignments and sizes for the card and issue detail title/finished toggle
- Removes alert messages for …

Issue UI adjustments for "Mark as finished"

---

Gemfile
Gemfile.lock
app/components/issue/finish_toggle_component.html.erb
app/components/issue/finish_toggle_component.rb
app/views/issues/_issue_detail.html.erb
app/views/visualizations/_card.html.erb
config/locales/activerecord.en.yml
config/locales/activerecord.pt-BR.yml

This PR extracts the issue finish toggle to a view component and changes the issue detail and the card to use it.
In the PRO Version the toggle already is a React component (Board and GRID). 
Here I decided to go with a Rails view component because more components will be added in the future and keep things simple for this FREE version.
Bonus: I've added a missing translation for the issue `finished_at` attribute

ref: changes issue finish toggle to use view_component

---

app/assets/tailwind/themes/_components/all.css
app/assets/tailwind/themes/_components/tab.css
app/controllers/profiles_controller.rb
app/javascript/controllers/time_entry/time_input_formatter_controller.js
app/models/user.rb
app/models/user/preferences.rb
app/views/time_entries/_form.html.erb
config/locales/activerecord.en.yml
config/locales/activerecord.pt-BR.yml
config/routes.rb
db/migrate/20250805210945_create_user_preferences.rb
db/schema.rb
spec/controllers/profiles_controller_spec.rb
spec/features/time_entries/custom_time_format_spec.rb
spec/features/time_entries/managing_time_entries_from_time_workspace_spec.rb
spec/models/user/preferences_spec.rb

This allows the user to input the 'total logged time' for a time entry in hours or minutes. 
The user can select their favorite input method (minutes or hours) 
- Created a user_preferences table with time_entry_time_format column. (
- Added a `tab.css` component (useful for the future layout/components refactoring) 
- Created a update_preferences generic endpoint on ProfilesController 
- Changed the Time Entry form to have a placeholder input showing the value in minutes or hours while the real 'total logged time in minutes' remains hidden. 
- The "favorite_theme" can be moved to the user_preferences in a future PR

Custom input format for logged time in time entries

---

spec/features/time_entries/custom_time_format_spec.rb
spec/support/helpers/wait_for_ajax_responses.rb

The specs were flaky because the assertion that was checking if the database was updated was being made before the request/update was completed.
I've added a helper to wait for the turbo frame response to complete, by checking the presence of the turbo-frame[busy] attribute (https://turbo.hotwired.dev/handbook/frames#eager-loading-frames)

chore: fix flaky time input preference specs
