Eigenfocus/eigenfocus

- app/models/app_metadata.rb
- lib/app_version_updater.rb
- spec/lib/app_version_updater_spec.rb
- spec/models/app_metadata_spec.rb
- spec/rails_helper.rb
This is important because the user could be following a installation guide for an older release.
> feat: update check after installation

- app/javascript/controllers/visualization/board/card_controller.js
- app/views/visualizations/_card.html.erb
- app/views/visualizations/_column.html.erb
- app/views/visualizations/show.html.erb
- config/importmap.rb
When the user visits the an issue URL that opens the issue modal, the board scrolls corresponding issue column where the issue card is.
> feat(Boards): visiting the issue URL, scrolls the board to the card

- app/assets/tailwind/themes/select2.css
- app/helpers/application_helper/icons.rb
- app/views/projects/_navigation_header.html.erb
- app/views/projects/_project.html.erb
- app/views/time_entries/_form_project_dependent_fields.html.erb
- config/locales/app.en.yml
- config/locales/app.pt-BR.yml
- spec/features/managing_kanban_spec.rb
This PR:
- Changes button styles on the project list
- Add a new 'go to issue list' button to a project item
- Add icons on visualizations tab
- Time entry form: Fixes single select2 text position / Updates board icon
> chore: better navigation between visualizations 

- app/models/visualization.rb
- app/views/visualizations/_favorite_labels_dropdown.html.erb
- app/views/visualizations/_favorite_labels_dropdown_list.html.erb
This PR brings live updates for favorite labels:
- It updates the dropdown without closing it
> feat: live update for favorite issue labels dropdown

- app/views/layouts/_sidebar.html.erb
- config/locales/application.layout.en.yml
- config/locales/application.layout.pt-BR.yml
> feat: adds link to all projects in the projects submenu on sidebar

- app/views/layouts/_header/_notification.html.erb
- app/views/layouts/_header/_notification_item.html.erb
- config/brakeman.ignore
- config/locales/application.layout.en.yml
- config/locales/application.layout.pt-BR.yml
This PR changes links appearance and positions on notifications list and allows more customizable html content.
> chore: formats notification list layout

- Gemfile
- Gemfile.lock
- app/assets/tailwind/themes/default.config.js
- app/views/layouts/application.html.erb
- config/i18n.yml
- config/initializers/i18njs.rb
- frontend/shared/dispatcher-hooks.js
- frontend/shared/i18n.js.erb
- frontend/shared/routes.js.erb
This PR brings more code from the PRO Edition and adds frontend service helpers: 
- Router methods coming from Rails routes
- Translations coming from Rails locales
- Custom React hook to be used with our dispatcher architecture
> chore: Setup frontend shared services

- app/assets/tailwind/themes/_components/markdown-editor/components/typograph.css
- frontend/components/MarkdownEditor/configure/menu.js
This PR: 
- Changes / Reorganizes markdown editor menu itens
- Changes markdown editor text sizes
> chore: Markdown enhancements

- app/controllers/survey_responses_controller.rb
- app/jobs/submit_survey_response_job.rb
- app/views/profiles/_onboarding_survey.html.erb
- config/locales/actions.en.yml
- config/locales/actions.pt-br.yml
- spec/features/answering_surveys_spec.rb
- spec/jobs/submit_survey_response_job_spec.rb
This PR: 
- Adds how did you found us to onboarding survey
- The `_onboarding_survey.html.erb` file has a lot of changes because I've fixed a wrong tabulation.
- Changes survey submit job to send these responses
> Adds how did you found us to onboarding survey

- app/assets/tailwind/themes/_components/focus-app/focus-app.css
- frontend/components/FocusSpace/PomodoroTimer/PomodoroTimer.js
This PR:
- Changes the button icon color for better contrast in dark themes
- Changes the notification icons colors for better contrast in dark themes
- Increases timer playing time to 7s
> Focus app button UI/UX enhancements

- app/assets/tailwind/themes/_components/focus-app/all.css
- app/assets/tailwind/themes/_components/focus-app/fireflies.css
- app/assets/tailwind/themes/_components/focus-app/focus-space.css
- app/assets/tailwind/themes/_components/welcome-screen.css
- app/views/layouts/application.html.erb
- app/views/profiles/_setup_welcome.html.erb
- frontend/components/FocusSpace/FocusSpace.js
This PR adds: 
- Wave animation to welcome screen
- Zen fireflies animations to focus space
> Adds UI background animations to welcome & focus space

- app/assets/tailwind/themes/_components/link.css
- app/views/projects/_project.html.erb
- app/views/projects/issues/_issue.html.erb
Changes: 
- Adds a link to the "All issues lists" on the project name inside the projects listing
- Adds a link to the "Issue Detail" on issue name inside the issues list
- Removes wrong css styles for visited links
> Quick improvements on projects/issues usability

- app/assets/tailwind/themes/_components/all.css
- app/assets/tailwind/themes/_components/sidebar.css
- app/views/layouts/_sidebar/_projects_menu.html.erb
Changes:
- Refactor sidebar menu to have a dedicated css file
- Adds a bottom fade to the project list
> Adds gradient to sidebar list links

- app/javascript/controllers/application.js
- app/views/projects/issues/_issue.html.erb
- app/views/projects/issues/index.html.erb
- Changes all issue list columns
- Fixes case where closing confirmation modal also closes the issue modal
> Adjustments to issue UI

- app/assets/tailwind/themes/_components/issue-detail.css
- app/assets/tailwind/themes/base.css
- app/assets/tailwind/themes/milkdown.css
- app/javascript/controllers/issue/comments_controller.js
- app/views/issues/_issue_detail.html.erb
- app/views/issues/comments/_comment.html.erb
- app/views/issues/comments/_form.html.erb
- app/views/issues/comments/create.turbo_stream.erb
- app/views/issues/comments/destroy.turbo_stream.erb
- app/views/issues/comments/update.turbo_stream.erb
- app/views/issues/issue_detail/_grouping_picker.html.erb
- app/views/issues/issue_detail/_main_form.html.erb
- app/views/issues/issue_detail/_right_sidebar.html.erb
- config/locales/actions.en.yml
- config/locales/actions.pt-br.yml
- frontend/components/MarkdownEditor.js
This PR: 
- Fixes modal title bg color on dark themes
- Moves group picker to the top left position
- Adds markdown to comments
> Issue modal improvements

- Gemfile
- app/controllers/issues/comments_controller.rb
- app/models/issue.rb
- app/models/issue/comment.rb
- app/views/visualizations/groupings/_card/_icons.html.erb
- db/migrate/20250503213952_create_issue_comments.rb
- db/migrate/20250504124033_add_comments_count_to_issues.rb
- db/schema.rb
- spec/factories/issue_comment.rb
- spec/features/issues/comments_spec.rb
- spec/features/project_management/using_views/kanban/purging_issues_spec.rb
This PR:
- Shows the number of comments on a given issue card
- Updates the comment count in real time (Not working when removing. But it's not worth the debug time because it should work with new React board)
- Refactors comment user to author
> Shows comments count on issue card

- app/assets/tailwind/themes/kernel-mindset/application.css
- app/assets/tailwind/themes/kernel-mindset/tailwind.config.js
- app/assets/tailwind/themes/noir-flow/tailwind.config.js
- app/helpers/application_helper/due_date.rb
- app/views/visualizations/_card.html.erb
Changes:
- Updates some theme colors to better match issue due date urgency
- Changes body text font in kernel mindset to be more readable
> Themes colors and fonts adjustments for due dates

- app/javascript/app-tours/index.js
- app/javascript/app-tours/time_entries_tours.en.js
- app/views/time_entries/index.html.erb
Changes:
- Dynamicly add a new time entry to the list when time entry tour starts
- Cancel all pending tours when the user clicks on the skip button
> App Tours improvements

- app/assets/tailwind/themes/_components/all.css
- app/assets/tailwind/themes/_components/issue/all.css
- app/assets/tailwind/themes/_components/issue/card.css
- app/assets/tailwind/themes/_components/issue/finish-check.css
- app/controllers/application_controller.rb
- app/controllers/issues_controller.rb
- app/helpers/application_helper/issues.rb
- app/javascript/controllers/animation_controller.js
- app/javascript/controllers/issue/finish_check_controller.js
- app/models/issue.rb
- app/views/issues/_issue_detail.html.erb
- app/views/visualizations/_card.html.erb
- config/locales/app.en.yml
- config/locales/app.pt-BR.yml
- config/routes.rb
- db/migrate/20250529171219_add_finished_at_to_issues.rb
- db/schema.rb
- spec/factories/issue.rb
- spec/features/issues/mark_as_finished_spec.rb
- spec/features/project_management/using_views/kanban/mark_as_finished_spec.rb
> Finish the work, otherwise an unfinished work will finish you
Amit Kalantri
But how can we actually finish an issue on Eigenfocus? Move to the far right column? Archive it? Both doesn't look like the action we are search, which is to finish the work.
Joke aside, this PR allows us to mark issues as finished on the issue detail or directly in the board view modal
On the issue details modal
On the board view
- Add way for filter finished issues and filter all unfinished issues on the all issues list
- Mass finish action for column menu(?)
> Mark issue as done

- app/helpers/application_helper/icons.rb
- app/models/issue.rb
- app/views/projects/issues/_filter.html.erb
- app/views/projects/issues/_issue.html.erb
- config/locales/actions.en.yml
- config/locales/actions.pt-br.yml
- spec/features/project_management/all_issues/listing_issues_spec.rb
This PR adds the finished filter and visual indication for issues finished
> Finished filter
